version: '3.4'
services:
  #------------------------
  #--- Jupyter Notebook ---
  #------------------------
  notebook:
    build:
      context: ./jupyter-notebook-docker
    ports:
      - "8888:8888"
    depends_on: 
      - mlflow
      - luigi
    environment: 
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes: 
      - file-store:/root/projects
    command: jupyter lab --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='dslab'
  #------------------------
  #---   Luigi Server   ---
  #------------------------
  luigi:
    build:
      context: ./jupyter-notebook-docker
    ports:
      - "8082:8082"
    depends_on: 
      - mlflow
    volumes: 
      - file-store:/root/projects
    command: luigid
  #----------------------    
  #--- ML Flow Server ---
  #----------------------
  mlflow:
    build:
      context: ./ml-flow-docker
    expose: 
      - "5000"
    ports:
      - "5000:5000"
    depends_on: 
      - postgres
    volumes: 
      - file-store:/mlflow
  #-------------------
  #--- Postgres DB ---
  #-------------------
  postgres:
    build:
      context: ./postgres-docker
    restart: always
    environment:
        POSTGRES_PASSWORD: 'admin'
    ports: 
      - "5433:5432"
    volumes:
      - ./postgres-store:/var/lib/postgresql/data

volumes:
  postgres-store:
    external: true
  file-store:
    external: true
    
